# Generated by Django 3.1 on 2020-08-29 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('login', models.CharField(max_length=250, verbose_name='login')),
                ('github_id', models.IntegerField(verbose_name='github_id')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('data', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('gist_id', models.CharField(max_length=250, verbose_name='gist_id')),
                ('description', models.TextField()),
                ('data', models.JSONField()),
                ('github_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gist', to='stats.githubuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('event_id', models.CharField(max_length=250, verbose_name='event_id')),
                ('github_type', models.CharField(max_length=250, verbose_name='github_type')),
                ('data', models.JSONField()),
                ('github_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='stats.githubuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
