DROP DATABASE IF EXISTS git4nstats;

CREATE DATABASE git4nstats
   WITH OWNER postgres
   TEMPLATE template0
   ENCODING 'UTF8'
   TABLESPACE  pg_default
   LC_COLLATE  'C'
   LC_CTYPE  'C'
   CONNECTION LIMIT  -1;